<a href="https://colab.research.google.com/github/vuke123/Data-processing/blob/main/Bioinformatics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Obrada informacija

## Laboratorijska vježba 2

U ovoj vježbi upoznat ćete se s jednom primjenom tehnika obrade informacija u bioinformatici. Ova laboratorijska vježba nosi 4 boda. Izvješće s ove laboratorijske vježbe potrebno je predati u .pdf formatu na *Moodle*. Izvješće koje predajete se mora zvati *PrezimeIme.pdf*. 

Osim biblioteka za rad s Fourierovom transformacijom (koristit ćemo samo numpy) koristit ćemo i biblioteku biopython koja sadrži puno korisnih alata iz područja bioinformatike. Mi ćemo je koristiti za jednostavnije baratanje bioinformatičkim tipovima podataka.

Biblioteka biopython dolazi s instalacijom Anaconde, ali ju je potrebno uključiti u okolinu (*environment*) koja se koristi.

Ako vježbu izvodite u Google Colab okruženju, morate instalirati biblioteku biopython. Instalaciju je potrebno izvršiti u sklopu prvog zadatka ove laboratorijske vježbe. Instalaciju izvodite sljedećim kodom: 

    try:
      import google.colab
      !pip install biopython
    except ImportError:
      pass

Nakon izvođenja ovog koda, možete učitati biopython biblioteku. 

1. Zadatak

Python biblioteke potrebne za laboratorijske vježbe su numpy i biopython. Uključite ih ("importirajte") i ispišite verziju svake od njih pomoću \[ime_biblioteke\].__version__.

UPUTA: Osnovna biopython biblioteka ima naziv Bio.

In [5]:
try:
  import google.colab
  !pip install biopython
except ImportError:
  pass 



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 3.1 MB 4.3 MB/s 


2. Zadatak

Uz laboratorijske vježbe dobili ste dvije datoteke s podacima. Datoteku koja sadrži referentni genom jednog soja bakterije  Escherichia coli (escherichia_coli_reference.fasta) u FASTA formatu i datoteku koja sadrži skup očitanja dobivenih sekvenciranjem (ecoli_ILL_small.fastq) u FASTQ formatu.

Datoteke možete učitati koristeći metodu _parse()_ iz biblioteke Bio.SeqIO. Metoda _parse()_ vraća iterator koji možete pretvoriti u Python listu na sljedeći način:

    reads = list(parse("ime_datoteke", "tip_datoteke"))

Tip datoteke postavite na "fasta" ili "fastq".

Učitajte obje datoteke te ispišite broj zapisa u svakoj od njih (broj elemenata u listi). Datoteka koja sadrži referencu trebala bi imati samo jedan zapis, dok bi datoteka s očitanjima trebala sadržavati veći broj zapisa.

NAPOMENA: Ako niste sigurni kako pronaći datoteke na disku iz Jupyter notebook-a, uvijek možete provjeriti radni direktorij sljedećim naredbama:

    import os
    os.getcwd()

i promijeniti ga sa:

    os.chdir()

Ako pak radite u Google Colab okruženju, koristite upute za učitavanje datoteka s Google diska iz prve laboratorijske vježbe. 

In [6]:
import numpy as np, Bio
print(np.version)
print(Bio.__version__)

<module 'numpy.version' from '/usr/local/lib/python3.8/dist-packages/numpy/version.py'>
1.80


In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
import os 
os.getcwd()
from Bio import SeqIO

In [9]:
reference = list(SeqIO.parse("drive/My Drive/Colab Notebooks/escherichia_coli_reference.fasta", "fasta"))
sample = list(SeqIO.parse("drive/My Drive/Colab Notebooks/ecoli_ILL_small.fastq", "fastq"))
print('Duljina liste ocitanja -> ' + str(len(sample)))
print('Duljina liste za referentni genom -> ' + str(len(reference)))

Duljina liste ocitanja -> 38585
Duljina liste za referentni genom -> 1


3. Zadatak

Svaki zapis koji ste učitali pomoću metode _Bio.SeqIO.parse()_ sadrži Veći broj podataka od kojih su nam bitni samo neki. Naredbom print ispišite cijeli prvi zapis iz datoteke s očitanjima i iz datoteke s referencom.

Vidjet ćete da oba zapisa (među ostalim podacima) sadrže identifikator zapisa i sekvencu. Identifikator zapisa možete dohvatiti pomoću

    zapis.id

dok sekvencu možete dohvatiti pomoću

    zapis.seq

Ispišite identifikator i sekvencu za prvo očitanje te identifikator i prvih 200 znakova za referentni genom E.coli.

NAPOMENA: Referentni genom Escherichia coli je dugačak oko 4.5 milijuna slova

In [10]:
print('Cijeli prvi zapis iz datoteke s referencom -> '  , str(reference[0]))
print('------------')
print('Cijeli prvi zapis iz datoteke s ocitanjima -> ' , sample[0])


Cijeli prvi zapis iz datoteke s referencom ->  ID: NC_000913.3
Name: NC_000913.3
Description: NC_000913.3 Escherichia coli str. K-12 substr. MG1655, complete genome
Number of features: 0
Seq('AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAG...TTC')
------------
Cijeli prvi zapis iz datoteke s ocitanjima ->  ID: SRR2052522.671
Name: SRR2052522.671
Description: SRR2052522.671 HWI-EAS390_0001:4:1:6915:1123/1
Number of features: 0
Per letter annotation for: phred_quality
Seq('GATCTGGTGACCGGGTCGCGCAAAGTGATCATCGCCATGGAACATTGCGCCAAA...TGC')


In [12]:
print('Identifikator i sekvenca za prvo očitanje --> ') 
sample1_ID = sample[0].id
print(sample1_ID)
print(sample[0].seq)
print('Identifikator i prvih 200 znakova za genom E.coli ---> ')
print(reference[0].id)
print(reference[0].seq[0:200])

Identifikator i sekvenca za prvo očitanje --> 
SRR2052522.671
GATCTGGTGACCGGGTCGCGCAAAGTGATCATCGCCATGGAACATTGCGCCAAAGATGGTTCAGCAAAAATTTTGGGCCTCTGTATCATGCCACTCACTGCGCAATATCCGGATCAAATGC
Identifikator i prvih 200 znakova za genom E.coli ---> 
NC_000913.3
AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGACAGATAAAAATTACAGAGTACACAACATCCATGAAACGCAT


4. Zadatak

Da bismo sekvence DNA analizirali metodama obrade signala, moramo pojednim nukleotidima (slovima) dodijeliti brojčane vrijednosti. Napišite funkciju u Pythonu koja će primiti slovo koje predstavlja nukleotid i vratiti odgovarajuću brojčanu vrijednost. Vrijednosti dodijelite na sljedeći način:

- A =  3
- G =  2
- C = -2
- T = -3

DNA sekvence mogu sadržavati i neke druge znakove (npr. 'N' koji označava da taj nuklotid nije poznat), njima dodijelite vrijednost 0. Također se može dogoditi da nukleotidi budu označeni i malim slovima, pa vodite računa da vaša funkcija mora vratiti ispravnu vrijendost i u tom slučaju.

In [13]:
def returnValue(letter): 
    if letter == 'A' or letter == 'a':
      return 3
    elif letter == 'G' or letter == 'g':
      return 2
    elif letter == 'C' or letter == 'c':
      return -2
    elif letter == 'T' or letter == 't':
      return -3
    else:
      return 0

In [14]:
print(type(sample[0].seq))
print('----')
print(type(reference[0].seq[0:200]))

<class 'Bio.Seq.Seq'>
----
<class 'Bio.Seq.Seq'>


5. Zadatak

Upotrebite napisanu funkciju da bi od prvog očitanja i od reference kreirali signal. Izračunajte korelaciju pomoću Fourierove transformacije. Zanemarite imaginarne vrijednosti.

In [15]:
x1 = [returnValue(s) for s in sample[0].seq]
x2 = [returnValue(s) for s in reference[0].seq]
len1 = len(x1)
len2 = len(x2)
array = [3,2,-2,-3]
k_arr = range(-len2+1,len1)
padding1 = [0]*(len2-1)
padding2 = [0]*(len1-1)
avg = np.average(array)
std = np.std(array)
x1 = [(x-avg)/std for x in x1]
x2 = [(x-avg)/std for x in x2]
X1 = np.fft.fft(padding1+x1)
X2 = np.fft.fft(x2+padding2)
Cor = np.conjugate(X2)*X1
cor = np.fft.ifft(Cor)
print('Korelacija -> ')
print(cor)
cor1 = cor
type(cor)

Korelacija -> 
[-0.61538462-4.88498131e-15j -1.84615385-3.62323912e-15j
 -1.38461538+7.34221076e-15j ... -0.15384615-4.71707354e-17j
  0.30769231+6.55936279e-15j -0.92307692-2.69980402e-15j]


numpy.ndarray

6. Zadatak

Ispišite duljinu reference. Koristeći metode biblioteke _numpy_, izračunajte srednju vrijednost i standardnu devijaciju duljine očitanja (uzmite u obzir sva očitanja).

Primijetit ćete da su sva očitanja jednake duljine.

In [17]:
print(len(x2))
sample_seqs = [y.seq for y in sample]
type(sample_seqs[0])
sample_length = []
for x in sample_seqs: 
  sample_length.append(len(x))

4641652


In [19]:
sample_mean = np.mean(sample_length)
sample_stdev = np.std(sample_length)
print(sample_mean)
print(sample_stdev)

121.0
0.0


7. zadatak

Što ako želimo izračunati korelaciju za veći broj očitanja i istu referencu? To je tipičan slučaj u bioinformatici jer uređaji za sekvenciranje proizvode tisuće i desetke tisuća očitanja koja se potom mapiraju na istu referencu.

Ako korelaciju računamo izravno, potrebno ju je svaki put izračunati iz početka. Ako korelaciju računamo pomoću FFT-a, transformaciju za referencu potrebno je napraviti samo jednom.

Izračunajte korelacije za prvih 10 očitanja.

In [23]:
def calcCor(some_sample):
  x1 = [returnValue(s) for s in some_sample.seq]
  x1 = [(x-avg)/std for x in x1]
  X1 = np.fft.fft(padding1+x1)
  Cor = np.conjugate(X2)*X1
  cor = np.fft.ifft(Cor)
  return cor

In [28]:
list_of_cor = map(calcCor, sample[0:10])

for i, cor in enumerate(list_of_cor): 
  print("Korelacija("+ str(i) + ") -->")
  print(cor)

Korelacija(0) -->
[-0.61538462-4.88498131e-15j -1.84615385-3.62323912e-15j
 -1.38461538+7.34221076e-15j ... -0.15384615-4.71707354e-17j
  0.30769231+6.55936279e-15j -0.92307692-2.69980402e-15j]
Korelacija(1) -->
[-9.23076923e-01-8.88178420e-16j -2.00000000e+00-1.70998183e-14j
 -1.38461538e+00+9.56266697e-15j ... -2.92307692e+00-9.33386601e-15j
  1.33232053e-15-1.95399216e-14j  1.38461538e+00+6.04808936e-15j]
Korelacija(2) -->
[-0.61538462-3.55271368e-15j -1.53846154-3.31542756e-15j
 -2.76923077+2.69404165e-15j ... -1.69230769-5.18900854e-16j
 -2.        -5.33240613e-15j -0.92307692-1.18036207e-14j]
Korelacija(3) -->
[-0.92307692+7.21644966e-15j -0.76923077+9.00042620e-15j
 -1.38461538+3.34536806e-15j ... -0.92307692+2.38142635e-15j
 -0.46153846-9.57269415e-16j  1.38461538-5.72027512e-15j]
Korelacija(4) -->
[-9.23076923e-01+7.10542736e-15j -7.69230769e-01+1.34413178e-14j
  1.53846154e-01+2.39147206e-15j ... -2.46153846e+00-1.64287800e-15j
  6.66139465e-15-2.08721748e-14j  1.38461538e+00

8. zadatak

Na temelju najveće vrijednosti korelacije između reference i prvog očitanja pronađite poziciju na referenci koja je najsličnija očitanju. Pozicija odgovara vrijednosti parametra k za koji je korelacija najveća.

Napišite metodu koja će primiti dva niza znakova jednake duljine, usporediti znakove na istim pozicijama i vratiti broj razlika (Hammingova udaljenost).

"Izrežite" dio reference koji je najsličniji očitanju (iste duljine kao i očitanje) i usporedite ga s očitanjem pomoću napisane funkcije.

In [29]:
k = k_arr[cor1.argmax()]
print("k={}".format(k))

def hamming_distance(niz1, niz2): 
  diff = 0
  for n in range(len(niz1)):
      if niz1[n] != niz2[n]:
         diff = diff + 1
  return diff

x1 = [returnValue(s) for s in sample[0].seq]
x2 = [returnValue(s) for s in reference[0].seq]
x2_trimmed = x2[abs(k):abs(k) + len(x1)]
print(hamming_distance(x1, x2_trimmed))


k=-2324486
9


9. zadatak

U datoteci "ecoli_ILL_small_aln.sam" dana su već izračunata poravnanja svih očitanja na referencu u SAM formatu. SAM je tekstualni "tab separated" format. U prvom stupcu se nalati identifikator očitanja, dok se u četvrtom stupcu nalazi pozicija na referenci na koju je očitanje najbolje poravnato (ostali stupci nas ne zanimaju). Također, datoteka s poravnanjima sadrži i nekoliko _header_ readaka kojima prvi stupac počinje sa znakom '@', njih također možete zanemariti.

Otvorite datoteku s poravnanjima i pronađite poravnanje za prvo očitanje (identifikator očitanja u datoteci s očitanjima i datoteci s poravnanjima mora biti jednak). Usporedite poziciju u datoteci sa pozicijom koju ste dobili pomoću korelacije.

UPOUTA: TSV datoteke možete otvoriti na sljedeći način:

    tsv_file = open("file_name")
    tsv_rows = csv.reader(tsv_file, delimiter="\t")

Varijabla _tsv\_rows_ će sadržavati listu redaka, a svaki redak biti lista vrijednosti (po jedna za svaki stupac).

In [30]:
import csv
tsv_file = open("drive/My Drive/Colab Notebooks/ecoli_ILL_small_aln.sam")
tsv_rows = csv.reader(tsv_file, delimiter="\t")
for row in tsv_rows: 
  if row[0] == sample1_ID:
    first_row = row
    break


print("---------------")
print("Pozicija u datoteci --> ", first_row[3])  
print("Za prvo očitanje pozicija dobivena pomoću korelacije je 2324486, dok je pozicija u datoteci s poravnanjima 2324487. Razlikuju se samo za 1 pa možemo zaključiti da nam je korelacija dala dobru poziciju za poravnanje.")

---------------
Pozicija u datoteci -->  2324487
Za prvo očitanje pozicija dobivena pomoću korelacije je 2324486, dok je pozicija u datoteci s poravnanjima 2324487. Razlikuju se samo za 1 pa možemo zaključiti da nam je korelacija dala dobru poziciju za poravnanje.


10. zadatak

Za prvo očitanje pozicija dobivena pomoću korelacije trabala bi biti 2324486, dok je pozicija u datoteci s poravnanjima 2324487. Razlikuju se samo za 1 pa možemo zaključiti da nam je korelacija dala dobru poziciju za poravnanje.

Prisjetimo se da korelacija ne računa točno poravnanje već ju koristimo samo da bi našli kandidatne pozicije za točno računanje. Tek onda na takvim pozicijama možemo točno poravnanje izračunati pomoću algoritama dinamičkog programiranja. Ako bi primijenili dinamičko programiranje za računanje poravnanja očitanja s cijelom referencom, postupak bi bio znatno sporiji i zahtijevao bi veliku količinu radne memorije.

**Ako želite** to možete isprobati pomoću algoritama za poravnanje u biblioteci _bioparser_. Lokalno poravnanje možete izračunati metodom:

    Bio.pairwise2.align.localxx(seq1, seq2)

Za prvih 100 očitanja izračunajte korelaciju te pomoću korelacije poziciju najveće sličnosti očitanja i reference. Usporedite rezultat sa podacima u datoteci s poravnanjima. Ispišite broj očitanja za koja se dvije pozicije razlikuju za najviše 5 mjesta.

In [32]:
sum = 0
first100k = {} 

for n in range(100): 
  cor = calcCor(sample[n])
  first100k[sample[n].id] = k_arr[cor.argmax()]

for row in tsv_rows: 
   id = row[0]
   if(id in first100k.keys()):
     if (abs(int(row[3]) - first100k[id]) < 6 ): 
       sum = sum + 1
       
print("Broj ocitanja za koje se pozicije razliku za max 5 mjesta --> ", sum)  


Broj ocitanja za koje se pozicije razliku za max 5 mjesta -->  0
